
###export PKG_CONFIG_PATH += /usr/local/lib/pkgconfig
###export ARCH += arm64
###export CROSS_COMPILE += /usr/bin/aarch64-linux-gnu-gcc
###export JSON_C_DIR += /usr/local/


PWD = $(shell pwd)


TARGET = Ta5320G_TIMER

CC=aarch64-linux-gnu-gcc

CFLAGS += $(shell pkg-config --cflags json-c)
LDFLAGS += $(shell pkg-config --libs json-c)
##CFLAGS += $(--cflags json-c)
##LDFLAGS += $(--libs json-c)
LDFLAGS += -pthread


OBJS = 	./Ta5320G_TIMER.o \
				./Ta53M0.o \
				./m0Uart_rx.o \
				./m0Uart_tx.o \
				./getDcuParam.o \
				./TstA53M0.o


all: $(OBJS) $(TARGET)

$(TARGET): 
	$(CC) $(OBJS) $(LDFLAGS) $(CFLAGS) -o $@ 

clean:
	rm -f $(TARGET) *.elf *.gdb *.o
	rm -f $(OBJS)
